"use client";
import { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import Hls from "hls.js";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const stream="https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8";
const projects=[
 {title:"WI FIBER",category:"Telecom",image:"/projects/wi-fiber.png",kind:"Redesign de site existente",objective:"Modernizar a presença digital e tornar planos, cobertura e canais de atendimento mais fáceis de encontrar.",experience:"Uma interface mais atual, com hierarquia clara, chamadas para ação bem distribuídas e uma jornada comercial direta.",tags:["Redesign","UX","Responsivo"]},
 {title:"Meu Mundo Colorido",category:"Educação infantil",image:"/projects/meu-mundo-colorido.png",kind:"Projeto criado do zero",objective:"Apresentar o espaço infantil de forma acolhedora e transmitir segurança para as famílias desde o primeiro contato.",experience:"Cores, formas e conteúdo trabalham juntos para criar uma experiência alegre, afetiva e simples de navegar.",tags:["Estratégia","Identidade","Responsivo"]},
 {title:"Clínica Zauli",category:"Odontologia",image:"/projects/clinica-zauli.png",kind:"Projeto criado do zero",objective:"Fortalecer o posicionamento profissional da clínica e transformar credibilidade em intenção de agendamento.",experience:"Uma experiência sofisticada e humana, com leitura confortável, identidade consistente e foco nos tratamentos.",tags:["UX","Autoridade","Conversão"]},
 {title:"ATSOC",category:"Serviços para provedores",image:"/projects/atsoc.png",kind:"Projeto criado do zero",objective:"Explicar uma solução especializada de suporte de forma clara para gestores de provedores de internet.",experience:"Conteúdo comercial estruturado para reduzir dúvidas, demonstrar valor e conduzir o visitante ao diagnóstico.",tags:["Copy","Estratégia","Conversão"]}
];
const services=[
 ["01","Sites institucionais","Presença digital completa para posicionar sua marca, apresentar serviços e gerar novos contatos."],
 ["02","Landing pages","Páginas objetivas para campanhas, lançamentos e ofertas com foco em conversão."],
 ["03","Experiência digital","Conteúdo, navegação e interações pensados para tornar cada contato simples e memorável."],
 ["04","Evolução de sites","Melhorias visuais, responsividade e novas seções para sites que já estão no ar."]
];

function BackgroundVideo({flip=false}:{flip?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const video=ref.current;if(!video)return;let hls:Hls|undefined;if(Hls.isSupported()){hls=new Hls({enableWorker:true});hls.loadSource(stream);hls.attachMedia(video)}else if(video.canPlayType("application/vnd.apple.mpegurl"))video.src=stream;return()=>hls?.destroy()},[]);return <video ref={ref} autoPlay muted loop playsInline className={`bg-video ${flip?"video-flip":""}`}/>}

function SectionTitle({number,label,title,italic,text}:{number:string;label:string;title:string;italic:string;text:string}){return <motion.header initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.8}} className="section-title"><div><p><i/>{number} {label}</p><h2>{title} <em>{italic}</em></h2></div><span>{text}</span></motion.header>}

export default function Home(){const[scrolled,setScrolled]=useState(false);const{scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],["0%","100%"]);useEffect(()=>{const onScroll=()=>setScrolled(scrollY>100);addEventListener("scroll",onScroll);return()=>removeEventListener("scroll",onScroll)},[]);useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.timeline({defaults:{ease:"power3.out"}}).from(".name-reveal",{opacity:0,y:42,duration:1.1}).from(".blur-in",{opacity:0,filter:"blur(9px)",y:18,duration:.8,stagger:.09},"-=.65");gsap.to(".marquee-track",{xPercent:-50,duration:42,ease:"none",repeat:-1})});return()=>ctx.revert()},[]);return <main><motion.div className="page-progress" style={{width:progress}}/>
<nav className={scrolled?"scrolled":""}><a className="logo" href="#home"><span>VS</span></a><i/><div><a href="#home">Início</a><a href="#work">Projetos</a><a href="#services">Serviços</a><a href="#about">Sobre</a></div><i/><a className="say-hi" href="https://wa.me/5511918554289?text=Olá%20Vinicius%2C%20vi%20seu%20portfólio%20e%20quero%20conversar%20sobre%20um%20site." target="_blank" rel="noreferrer">Fale comigo <b>↗</b></a></nav>

<section id="home" className="hero"><BackgroundVideo/><div className="video-overlay"/><div className="video-fade"/><div className="hero-content"><p className="blur-in eyebrow">PORTFÓLIO 2026</p><h1 className="name-reveal">Vinicius <em>Scielzo</em></h1><p className="blur-in role">Sites que unem <em>estética</em>, clareza e experiência.</p><p className="blur-in description">Transformo ideias e negócios em experiências digitais que conquistam atenção, comunicam valor e facilitam o próximo passo do cliente.</p><div className="blur-in hero-actions"><a href="#work" className="button solid">Ver projetos</a><a href="https://wa.me/5511918554289?text=Olá%20Vinicius%2C%20vi%20seu%20portfólio%20e%20quero%20conversar%20sobre%20um%20site." target="_blank" rel="noreferrer" className="button outline">Começar um projeto</a></div></div><div className="scroll-cue">ROLAR<span><i/></span></div></section>

<section id="work" className="work-quick"><div className="section"><SectionTitle number="01" label="PROJETOS" title="Seu negócio pode" italic="parecer maior" text="Um bom site aumenta a confiança, explica melhor sua oferta e transforma interesse em contato. Veja alguns exemplos."/></div><div className="project-rail"><div className="rail-track">{[...projects,...projects].map((project,index)=><a href={`/projetos#${project.title.toLowerCase().replaceAll(" ","-")}`} className="rail-card" key={`${project.title}-${index}`}><img src={project.image} alt={`Site ${project.title}`}/><div className="rail-shade"/><div className="rail-info"><span>{project.kind}</span><h3>{project.title}</h3><p>{project.category}</p><b>CONHECER O PROJETO ↗</b></div></a>)}</div></div><div className="rail-footer"><span>CLIQUE PARA CONHECER CADA PROJETO</span><a href="/projetos">VER TODOS OS PROJETOS ↗</a></div></section>

<section id="services" className="section services"><SectionTitle number="02" label="SERVIÇOS" title="O que posso" italic="criar com você" text="Cada projeto começa pelo objetivo do negócio e termina com uma experiência pronta para apresentar, vender e crescer."/><div className="service-list">{services.map((item,index)=><motion.article key={item[1]} initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.55,delay:index*.05}}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p><b>↗</b></motion.article>)}</div></section>

<section id="about" className="about"><div className="about-orbit"><i/><i/><i/></div><div className="about-content"><p className="eyebrow">03 QUEM SOU</p><h2>Design com<br/><em>visão de cliente.</em></h2><div className="about-text"><p>Sou Vinicius Scielzo. Crio sites para negócios que precisam se apresentar melhor, transmitir confiança e facilitar a decisão do cliente.</p><p>Minha experiência com atendimento, suporte e experiência do cliente me ensinou a enxergar dúvidas, barreiras e expectativas antes de pensar na tela. Esse olhar orienta cada texto, seção e interação.</p></div><div className="principles"><span>Clareza</span><span>Experiência</span><span>Conversão</span></div></div></section>

<section className="section process"><SectionTitle number="04" label="PROCESSO" title="Da ideia ao" italic="site no ar" text="Um processo direto, colaborativo e sem complicação para transformar sua ideia em uma presença digital profissional."/><div className="process-grid">{[["01","Descoberta","Entendo sua marca, público e objetivo."],["02","Direção","Organizo conteúdo, estrutura e identidade visual."],["03","Criação","Construo a experiência em todos os tamanhos de tela."],["04","Publicação","Revisamos os detalhes e colocamos o site no ar."]].map(item=><article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>

<footer id="contact"><BackgroundVideo flip/><div className="footer-overlay"/><div className="marquee"><div className="marquee-track">{Array(5).fill("IDEIAS QUE GANHAM FORMA • SITES QUE GERAM CONFIANÇA • EXPERIÊNCIAS QUE MOVEM NEGÓCIOS • ").join("")}</div></div><div className="footer-content"><p className="eyebrow">TEM UM PROJETO EM MENTE?</p><h2>Vamos criar algo<br/><em>que sua marca mereça.</em></h2><p>Conte o que você precisa. Eu ajudo a transformar a ideia em uma experiência digital clara, bonita e funcional.</p><a className="button solid" href="https://wa.me/5511918554289?text=Olá%20Vinicius%2C%20vi%20seu%20portfólio%20e%20quero%20conversar%20sobre%20um%20site." target="_blank" rel="noreferrer">Conversar pelo WhatsApp ↗</a></div><div className="footer-bar"><span>© 2026 VINICIUS SCIELZO</span><span><i/> DISPONÍVEL PARA PROJETOS</span></div></footer><a className="whatsapp-float" href="https://wa.me/5511918554289?text=Olá%20Vinicius%2C%20vi%20seu%20portfólio%20e%20quero%20conversar%20sobre%20um%20site." target="_blank" rel="noreferrer" aria-label="Conversar com Vinicius pelo WhatsApp"><span className="whatsapp-copy"><b>Seu próximo site começa aqui</b><small>Conte sua ideia pelo WhatsApp</small></span><i className="whatsapp-icon"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.5 12.5 0 0 0-10.7 19L3.6 28.4l6.5-1.7A12.5 12.5 0 1 0 16 3Zm0 22.7c-2 0-3.8-.5-5.4-1.5l-.4-.2-3.8 1 1-3.7-.2-.4A10.2 10.2 0 1 1 16 25.7Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1a8.4 8.4 0 0 1-4.1-3.6c-.3-.5.3-.5.9-1.6.1-.2.1-.4 0-.6l-.9-2.2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.3 3.4 1.5 3.6c.2.2 2.5 3.8 6 5.3.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.7.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg></i></a></main>}
