"use client";
import { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import Hls from "hls.js";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const stream="https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8";
const whatsappBase="https://wa.me/5511918554289?text=";
const whatsapp=(message:string)=>whatsappBase+encodeURIComponent(message);
const mainMessage="Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre um site para minha empresa.";

const projects=[
 {id:"wi-fiber",title:"WI-FIBER",category:"Telecom",image:"/projects/wi-fiber.png",kind:"Redesign de site existente",live:"https://wi-fiber.vercel.app/"},
 {id:"meu-mundo-colorido",title:"Meu Mundo Colorido",category:"Educação infantil",image:"/projects/meu-mundo-colorido.png",kind:"Projeto criado do zero",live:"https://meumundocolorido.vercel.app/"},
 {id:"clínica-zauli",title:"Clínica Zauli",category:"Odontologia",image:"/projects/clinica-zauli.png",kind:"Projeto criado do zero",live:"https://clinicazauli-el3c.vercel.app/"},
 {id:"atsoc",title:"ATSOC",category:"Serviços para provedores",image:"/projects/atsoc.png",kind:"Projeto criado do zero",live:"https://www.atsoc.com.br/"}
];
const services=[
 ["01","Sites institucionais","Sites completos para apresentar sua empresa, serviços, diferenciais e canais de contato com clareza e profissionalismo."],
 ["02","Landing pages","Páginas direcionadas para campanhas, lançamentos ou ofertas, com estrutura focada em gerar contatos e oportunidades."],
 ["03","Experiência e conversão","Textos, navegação e chamadas para ação pensados para facilitar a decisão e conduzir o visitante ao próximo passo."],
 ["04","Redesign de sites","Modernização visual, reorganização de conteúdo e correção da experiência em celulares, tablets e computadores."]
];
const plans=[
 {name:"Essencial",price:"R$997",description:"Para empresas que precisam começar com uma presença digital profissional e objetiva.",button:"Começar com o Essencial",message:"Olá, Vinicius! Vi seu portfólio e gostaria de saber mais sobre o Site Essencial de R$997.",items:["Site de página única","Até 4 seções","Layout responsivo","Aplicação da identidade visual da empresa","Apresentação dos principais serviços","Botão de contato pelo WhatsApp","Integração com redes sociais","Configuração básica para mecanismos de busca","Conexão com domínio personalizado","Publicação do site","Uma rodada de ajustes","Entrega de 3 a 7 dias úteis, a depender da complexidade do site, após o recebimento de todos os materiais"]},
 {name:"Profissional",price:"R$1.497",featured:true,description:"Para empresas que precisam apresentar melhor seus serviços, diferenciais e canais de contato.",button:"Escolher o Profissional",message:"Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre o Site Profissional de R$1.497.",items:["Site institucional completo","Até 7 seções","Estrutura e direção visual personalizadas","Layout responsivo","Apresentação detalhada dos serviços","Botões e chamadas estratégicas para o WhatsApp","Formulário ou canal de contato funcional","Integração com redes sociais","Integração com localização ou mapa, quando necessário","Configuração básica para mecanismos de busca","Conexão com domínio personalizado","Publicação do site","Duas rodadas de ajustes","Entrega de 3 a 7 dias úteis, a depender da complexidade do site, após o recebimento de todos os materiais"]},
 {name:"Estratégico",price:"R$1.997",description:"Para empresas que precisam de uma presença digital mais completa, personalizada e preparada para crescer.",button:"Quero um site estratégico",message:"Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre o Site Estratégico de R$1.997.",items:["Site com até 3 páginas","Limite total de até 10 seções","Estrutura comercial e direção visual personalizadas","Organização e revisão comercial dos textos enviados","Layout responsivo","Apresentação detalhada de serviços e diferenciais","Chamadas estratégicas para conversão","Formulário ou canal de contato funcional","WhatsApp, redes sociais, localização e outras integrações simples","Animações e interações visuais personalizadas","Configuração básica de SEO para cada página","Conexão com domínio personalizado","Publicação do site","Duas rodadas de ajustes","Entrega de 3 a 7 dias úteis, a depender da complexidade do site, após o recebimento de todos os materiais"]}
];
const carePlans=[
 {name:"Essencial",price:"R$79",items:["Monitoramento de funcionamento","Hospedagem e renovação anual do domínio","Backup periódico","Correções técnicas","Suporte em horário comercial","Até 15 minutos mensais de alterações simples, sem cobrança adicional"]},
 {name:"Profissional",price:"R$119",featured:true,items:["Monitoramento de funcionamento","Hospedagem e renovação anual do domínio","Backup periódico","Correções técnicas","Atualizações necessárias","Suporte em horário comercial","Até 30 minutos mensais de alterações simples, sem cobrança adicional"]},
 {name:"Estratégico",price:"R$149",items:["Monitoramento de funcionamento","Hospedagem e renovação anual do domínio","Backup periódico","Correções técnicas","Atualizações necessárias","Suporte prioritário em horário comercial","Até 45 minutos mensais de alterações simples, sem cobrança adicional"]}
];
const commonRules=["Pagamento de 50% para iniciar e 50% antes da publicação","O prazo começa após o recebimento de todos os materiais","A configuração e conexão do domínio estão incluídas","O custo anual de registro do domínio, quando necessário, é pago separadamente","Funcionalidades, integrações, páginas ou seções fora do escopo são avaliadas separadamente","Loja virtual, área restrita, sistemas, banco de dados e integrações complexas não estão incluídos nesses planos","O cliente deverá fornecer informações, logotipo e imagens disponíveis","Auxilio na organização do conteúdo; produção fotográfica, criação de logotipo e redação extensa do zero são contratadas separadamente"];
const faqs=[
 ["Quanto tempo demora?","O prazo de entrega é de 3 a 7 dias úteis, a depender da complexidade do site, após o recebimento de todos os materiais."],
 ["O site funciona no celular?","Sim. Todos os projetos são desenvolvidos para funcionar em celulares, tablets, notebooks e computadores."],
 ["O domínio está incluído?","A configuração e conexão do domínio estão incluídas. Caso seja necessário registrar um novo domínio, o custo anual do endereço é pago separadamente."],
 ["Posso solicitar alterações?","O Site Essencial inclui uma rodada de ajustes. Os planos Profissional e Estratégico incluem duas rodadas. Após a entrega, pequenas alterações podem ser atendidas pelo cuidado contínuo."],
 ["O site aparecerá no Google?","O projeto recebe configuração básica para mecanismos de busca. O posicionamento depende da concorrência, conteúdo, autoridade do domínio e estratégias adicionais."],
 ["O que preciso enviar para começar?","Informações da empresa, serviços, contatos, logotipo, cores e imagens disponíveis. Caso algum conteúdo ainda não esteja organizado, eu ajudo a estruturar."],
 ["Como funciona o pagamento?","São 50% para iniciar o projeto e 50% antes da publicação."],
 ["Qual plano é mais indicado?","O Site Essencial é indicado para quem precisa iniciar com uma presença objetiva. O Site Profissional atende empresas que precisam apresentar melhor seus serviços e diferenciais. O Site Estratégico é recomendado para projetos com mais conteúdo, páginas e personalização."],
 ["Existe mensalidade?","Sim. Após a publicação, o cuidado contínuo inclui monitoramento, hospedagem, renovação anual do domínio, backup, correções e pequenas alterações dentro do tempo mensal de cada plano, sem cobranças adicionais. Novas páginas ou funcionalidades maiores são avaliadas separadamente."]
];

function BackgroundVideo({flip=false}:{flip?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const video=ref.current;if(!video)return;let hls:Hls|undefined;if(Hls.isSupported()){hls=new Hls({enableWorker:true});hls.loadSource(stream);hls.attachMedia(video)}else if(video.canPlayType("application/vnd.apple.mpegurl"))video.src=stream;return()=>hls?.destroy()},[]);return <video ref={ref} autoPlay muted loop playsInline className={`bg-video ${flip?"video-flip":""}`} aria-hidden="true"/>}
function SectionTitle({number,label,title,italic,text}:{number:string;label:string;title:string;italic:string;text:string}){return <motion.header initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.8}} className="section-title"><div><p><i/>{number} {label}</p><h2>{title} <em>{italic}</em></h2></div><span>{text}</span></motion.header>}
function ProjectRail(){const ref=useRef<HTMLDivElement>(null);const dragging=useRef(false);const startX=useRef(0);const startScroll=useRef(0);useEffect(()=>{const el=ref.current;if(!el)return;let frame=0;const move=()=>{if(!dragging.current){el.scrollLeft+=.45;if(el.scrollLeft>=el.scrollWidth/2)el.scrollLeft=0}frame=requestAnimationFrame(move)};frame=requestAnimationFrame(move);return()=>cancelAnimationFrame(frame)},[]);return <div className="project-rail" ref={ref} onPointerDown={e=>{dragging.current=true;startX.current=e.clientX;startScroll.current=e.currentTarget.scrollLeft}} onPointerMove={e=>{if(dragging.current)e.currentTarget.scrollLeft=startScroll.current-(e.clientX-startX.current)}} onPointerUp={()=>dragging.current=false} onPointerCancel={()=>dragging.current=false} onPointerLeave={()=>dragging.current=false}><div className="rail-track">{[...projects,...projects].map((project,index)=><a href={`/projetos#${project.id}`} className="rail-card" key={`${project.id}-${index}`}><img src={project.image} alt={`Site ${project.title}`} loading="lazy" draggable="false" width="1200" height="760"/><div className="rail-shade"/><div className="rail-info"><span>{project.kind}</span><h3>{project.title}</h3><p>{project.category}</p><b>CONHECER O PROJETO ↗</b></div></a>)}</div></div>}

export default function Home(){const[scrolled,setScrolled]=useState(false);const[menuOpen,setMenuOpen]=useState(false);const{scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],["0%","100%"]);useEffect(()=>{const onScroll=()=>setScrolled(scrollY>100);onScroll();addEventListener("scroll",onScroll);return()=>removeEventListener("scroll",onScroll)},[]);useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.timeline({defaults:{ease:"power3.out"}}).from(".name-reveal",{opacity:0,y:42,duration:1.1}).from(".blur-in",{opacity:0,filter:"blur(9px)",y:18,duration:.8,stagger:.09},"-=.65");gsap.to(".marquee-track",{xPercent:-50,duration:42,ease:"none",repeat:-1})});return()=>ctx.revert()},[]);return <main><motion.div className="page-progress" style={{width:progress}}/>
<nav className={scrolled?"scrolled":""}><a className="logo" href="#home" aria-label="Ir para o início"><span>VS</span></a><i/><button className="menu-toggle" onClick={()=>setMenuOpen(value=>!value)} aria-expanded={menuOpen} aria-label={menuOpen?"Fechar menu":"Abrir menu"}><span/><span/></button><div className={`nav-links ${menuOpen?"open":""}`}><a onClick={()=>setMenuOpen(false)} href="#home">Início</a><a onClick={()=>setMenuOpen(false)} href="#work">Projetos</a><a onClick={()=>setMenuOpen(false)} href="#services">Serviços</a><a onClick={()=>setMenuOpen(false)} href="#offer">Investimento</a><a onClick={()=>setMenuOpen(false)} href="#about">Sobre</a></div><i/><a className="say-hi" href={whatsapp(mainMessage)} target="_blank" rel="noopener noreferrer">Fale comigo <b>↗</b></a></nav>

<section id="home" className="hero"><BackgroundVideo/><div className="video-overlay"/><div className="video-fade"/><div className="hero-content"><p className="blur-in eyebrow hero-offer">SITES PROFISSIONAIS PARA EMPRESAS E NEGÓCIOS LOCAIS</p><h1 className="name-reveal">Vinicius <em>Scielzo</em></h1><p className="blur-in role">Sites que unem <em>estética</em>, clareza e experiência.</p><p className="blur-in description">Crio sites profissionais, responsivos e preparados para apresentar sua empresa, transmitir confiança e transformar visitantes em contatos pelo WhatsApp.</p><p className="blur-in trust-line">Responsivo em todos os dispositivos <i/> Publicado e pronto para divulgar</p><p className="blur-in starting-price"><strong>Sites profissionais a partir de R$997</strong> <i/> Entrega de 3 a 7 dias úteis</p><div className="blur-in hero-actions"><a href="#work" className="button solid">Ver projetos</a><a href={whatsapp(mainMessage)} target="_blank" rel="noopener noreferrer" className="button outline">Quero meu site</a></div></div><div className="scroll-cue">ROLAR<span><i/></span></div></section>

<section id="work" className="work-quick"><div className="section"><SectionTitle number="01" label="PROJETOS" title="Seu negócio pode" italic="parecer maior" text="Projetos reais criados para comunicar valor, aumentar a confiança e facilitar o contato de novos clientes."/></div><p className="rail-instruction">ARRASTE PARA EXPLORAR OS PROJETOS</p><ProjectRail/><div className="rail-footer"><span>SELECIONE UM PROJETO PARA CONHECER</span><a href="/projetos">VER TODOS OS PROJETOS ↗</a></div><div className="section-cta"><a className="button outline" href={whatsapp("Olá, Vinicius! Vi seus projetos e quero criar algo assim para minha empresa.")} target="_blank" rel="noopener noreferrer">Quero um projeto assim</a></div></section>

<section id="offer" className="commercial section"><SectionTitle number="02" label="INVESTIMENTO" title="Escolha o site ideal" italic="para o momento da sua empresa" text="Três opções de projeto, com escopos claros e a mesma preocupação com qualidade, responsividade e experiência do cliente."/><div className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<span className="plan-badge">Mais escolhido</span>}<p>SITE {plan.name.toUpperCase()}</p><h3>{plan.price}</h3><div className="plan-rule"/><strong>{plan.description}</strong><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul><a className={`button ${plan.featured?"solid":"outline"}`} href={whatsapp(plan.message)} target="_blank" rel="noopener noreferrer">{plan.button}</a></article>)}</div><div className="common-rules"><p>REGRAS COMUNS AOS TRÊS PLANOS</p><div>{commonRules.map(rule=><span key={rule}>{rule}</span>)}</div></div><div className="care-section"><header><p>CUIDADO CONTÍNUO</p><h3>Seu site continua cuidado <em>depois da publicação.</em></h3><span>Monitoramento, hospedagem, domínio, backup, correções e pequenos ajustes para manter sua presença digital sempre operante, sem cobranças adicionais dentro do escopo mensal.</span></header><div className="care-grid">{carePlans.map(plan=><article className={plan.featured?"featured":""} key={plan.name}>{plan.featured&&<span className="plan-badge">Mais escolhido</span>}<p>{plan.name}</p><h4>{plan.price}<small>/mês</small></h4><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div><small>Alterações não utilizadas não são acumulativas. Alterações simples dentro do tempo mensal, hospedagem e renovação anual do domínio estão incluídas. Novas páginas, seções, identidades visuais, funcionalidades ou integrações fora do escopo são orçadas separadamente.</small></div></section>

<section id="services" className="section services"><SectionTitle number="03" label="SERVIÇOS" title="O que posso" italic="criar com você" text="Soluções claras para empresas que precisam apresentar melhor seus serviços e transformar interesse em oportunidade."/><div className="service-list">{services.map((item,index)=><motion.article key={item[1]} initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.55,delay:index*.05}}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p><b>↗</b></motion.article>)}</div></section>

<section id="about" className="about"><div className="about-orbit"><i/><i/><i/></div><div className="about-content"><p className="eyebrow">04 QUEM SOU</p><h2>Design com<br/><em>visão de cliente.</em></h2><div className="about-text"><p>Sou Vinicius Scielzo. Minha experiência com atendimento, suporte, operações e experiência do cliente me ensinou a enxergar dúvidas, barreiras e expectativas antes de pensar na tela.</p><p>Crio sites que não são apenas bonitos: eles organizam informações, transmitem confiança e facilitam a decisão de quem está conhecendo a empresa.</p></div><div className="principles"><span>Clareza na comunicação</span><span>Visão de experiência do cliente</span><span>Acompanhamento até a publicação</span></div></div></section>

<section className="section process"><SectionTitle number="05" label="PROCESSO" title="Da ideia ao" italic="site no ar" text="Um processo direto e acompanhado para você saber exatamente o que acontece em cada etapa."/><div className="process-grid">{[["01","Descoberta","Entendo sua empresa, público, serviços, diferenciais e objetivo do projeto."],["02","Direção","Organizo o conteúdo, a estrutura, as referências e a identidade visual do site."],["03","Criação","Desenvolvo o projeto e adapto toda a experiência para celular, tablet e computador."],["04","Revisão e publicação","Apresento o site, realizo os ajustes previstos, conecto o domínio e coloco o projeto no ar."]].map(item=><article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div><p className="process-time">Prazo estimado: de 3 a 7 dias úteis, a depender da complexidade do site, após o recebimento de todos os materiais.</p></section>

<section className="section faq"><SectionTitle number="06" label="DÚVIDAS" title="Antes de começar" italic="seu projeto" text="Respostas diretas para as principais dúvidas sobre criação, entrega e publicação."/><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question}><summary><span>0{index+1}</span>{question}<b>+</b></summary><p>{answer}</p></details>)}</div></section>

<footer id="contact"><BackgroundVideo flip/><div className="footer-overlay"/><div className="marquee"><div className="marquee-track">{Array(5).fill("IDEIAS QUE GANHAM FORMA • SITES QUE GERAM CONFIANÇA • EXPERIÊNCIAS QUE MOVEM NEGÓCIOS • ").join("")}</div></div><div className="footer-content"><p className="eyebrow">TEM UM PROJETO EM MENTE?</p><h2>Vamos criar algo<br/><em>que sua marca mereça.</em></h2><p>Conte o que você precisa. Eu transformo sua ideia em uma experiência digital clara, profissional e pronta para gerar contatos.</p><a className="button solid" href={whatsapp(mainMessage)} target="_blank" rel="noopener noreferrer">Conversar pelo WhatsApp ↗</a></div><div className="footer-bar"><span>© {new Date().getFullYear()} VINICIUS SCIELZO <i/> SITES E EXPERIÊNCIA DIGITAL</span><span><i/> DISPONÍVEL PARA PROJETOS</span></div></footer>
<a className="whatsapp-float is-compact" href={whatsapp(mainMessage)} target="_blank" rel="noopener noreferrer" aria-label="Conversar com Vinicius pelo WhatsApp"><span className="whatsapp-copy"><b>Seu próximo site começa aqui</b><small>Conte sua ideia pelo WhatsApp</small></span><i className="whatsapp-icon"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.5 12.5 0 0 0-10.7 19L3.6 28.4l6.5-1.7A12.5 12.5 0 1 0 16 3Zm0 22.7c-2 0-3.8-.5-5.4-1.5l-.4-.2-3.8 1 1-3.7-.2-.4A10.2 10.2 0 1 1 16 25.7Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1a8.4 8.4 0 0 1-4.1-3.6c-.3-.5.3-.5.9-1.6.1-.2.1-.4 0-.6l-.9-2.2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.3 3.4 1.5 3.6c.2.2 2.5 3.8 6 5.3.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.7.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg></i></a>
</main>}
