import { useEffect, useRef } from "react";
import Hls from "hls.js";

const stream = "https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8";
const whatsappBase = "https://wa.me/5511918554289?text=";
const whatsapp = (message: string) => whatsappBase + encodeURIComponent(message);

const plans = [
  {name:"Presença Digital",price:"R$997",headline:"Comece com uma presença digital profissional.",description:"Para profissionais e empresas que precisam sair do básico e ter um espaço próprio na internet que transmita confiança, profissionalismo e facilite o contato de novos clientes.",ideal:"Quem ainda não possui site ou precisa de uma presença digital simples e profissional.",note:"Projeto objetivo, desenvolvido em página única.",deadline:"Entrega estimada de 3 a 7 dias úteis após o recebimento dos materiais.",button:"Quero minha presença digital",message:"Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre o plano Presença Digital de R$997.",items:["Presença profissional para sua marca na internet","Apresentação clara da empresa ou profissional","Destaque para seus principais serviços","Experiência adaptada para celular, tablet e computador","Contato facilitado pelo WhatsApp","Integração com suas redes sociais","Estrutura preparada para mecanismos de busca","Seu próprio domínio conectado ao site","Publicação e configuração do site","1 rodada de ajustes"]},
  {name:"Autoridade Digital",price:"R$1.497",featured:true,headline:"Apresente sua empresa com mais autoridade.",description:"Para empresas e profissionais que precisam apresentar melhor seus serviços, diferenciais e posicionamento, transmitindo mais confiança para quem chega pelo Google, indicação ou redes sociais.",ideal:"Quem quer transformar sua presença digital em uma apresentação profissional e comercial da empresa.",note:"Estrutura definida de acordo com a necessidade do projeto.",deadline:"Entrega estimada de 3 a 7 dias úteis após o recebimento dos materiais.",button:"Quero fortalecer minha marca",message:"Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre o plano Autoridade Digital de R$1.497.",items:["Estrutura pensada para valorizar sua empresa","Apresentação estratégica dos seus serviços","Destaque dos principais diferenciais","Construção de autoridade e confiança","Chamadas estratégicas para gerar contatos","WhatsApp integrado em pontos estratégicos","Provas sociais e avaliações de clientes","Formulário ou canal de contato","Integração com redes sociais","Localização ou mapa quando necessário","Estrutura preparada para mecanismos de busca","Domínio personalizado","Publicação e configuração do site","2 rodadas de ajustes"]},
  {name:"Posicionamento Estratégico",price:"R$1.997",headline:"Transforme seu site em uma ferramenta comercial.",description:"Para empresas que querem uma presença digital mais completa, personalizada e construída para valorizar a marca, apresentar suas soluções e gerar novas oportunidades de negócio.",ideal:"Empresas que querem utilizar o site como parte da estratégia comercial e de posicionamento.",note:"Estrutura e páginas definidas estrategicamente conforme a necessidade do projeto.",deadline:"Entrega estimada conforme a complexidade do projeto após o recebimento dos materiais.",button:"Quero um site estratégico",message:"Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre o plano Posicionamento Estratégico de R$1.997.",items:["Estratégia personalizada para o negócio","Estrutura pensada para conduzir o visitante","Posicionamento mais premium da marca","Organização comercial dos serviços e soluções","Revisão e melhoria dos textos enviados pelo cliente","Construção de argumentos de venda","Chamadas estratégicas para conversão","Provas sociais, diferenciais e autoridade","Jornada pensada para transformar visitantes em contatos","Formulários e canais de contato estratégicos","Estrutura preparada para campanhas futuras","Estrutura preparada para mecanismos de busca","Domínio personalizado","Publicação e configuração completa","Até 3 rodadas de ajustes"]},
];

const comparison = [
  {name:"Presença Digital",statement:"Preciso ter um site profissional.",value:"R$ 997"},
  {name:"Autoridade Digital",statement:"Quero apresentar melhor minha empresa e gerar mais confiança.",value:"R$ 1.497",featured:true},
  {name:"Posicionamento Estratégico",statement:"Quero que meu site também trabalhe comercialmente pela minha empresa.",value:"R$ 1.997"},
  {name:"Landing Page",statement:"Quero gerar contatos para uma oferta específica.",value:"Solicitar orçamento"},
];

const carePlans = [
  {name:"Cuidado Essencial",price:"R$69,90",items:["Hospedagem gerenciada do site","Renovação anual do domínio","Monitoramento de funcionamento","Backup periódico de segurança","Até 30 minutos mensais para correções e alterações simples","Atendimento em horário comercial"]},
  {name:"Cuidado Completo",price:"R$99,90",featured:true,items:["Hospedagem gerenciada do site","Renovação anual do domínio","Monitoramento de funcionamento","Backup periódico de segurança","Até 1 hora mensal para correções e alterações simples","Atendimento todos os dias, das 08h às 22h"]},
];

const commonRules = ["Pagamento de 50% para iniciar e 50% antes da publicação","O prazo começa após o recebimento de todos os materiais","A configuração e conexão do domínio estão incluídas","O custo anual de registro do domínio, quando necessário, é pago separadamente","Funcionalidades, integrações, páginas ou seções fora do escopo são avaliadas separadamente","Loja virtual, área restrita, sistemas, banco de dados e integrações complexas não estão incluídos nesses planos","O cliente deverá fornecer informações, logotipo e imagens disponíveis","Auxilio na organização do conteúdo; produção fotográfica, criação de logotipo e redação extensa do zero são contratadas separadamente"];

function BackgroundVideo({flip=false}:{flip?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const video=ref.current;if(!video)return;let hls:Hls|undefined;if(Hls.isSupported()){hls=new Hls({enableWorker:true});hls.loadSource(stream);hls.attachMedia(video)}else if(video.canPlayType("application/vnd.apple.mpegurl"))video.src=stream;return()=>hls?.destroy()},[]);return <video ref={ref} autoPlay muted loop playsInline className={`bg-video ${flip?"video-flip":""}`} aria-hidden="true"/>}

export default function Investment(){return <main className="projects-page pricing-page">
  <nav className="projects-nav pricing-nav"><a className="logo" href="/" aria-label="Voltar ao início"><span>VS</span></a><div className="pricing-nav-actions"><a href="/">← Voltar ao início</a><a href="/projetos">Ver projetos ↗</a></div><a className="say-hi" href={whatsapp("Olá, Vinicius! Vi as opções de investimento e gostaria de conversar sobre meu projeto.")} target="_blank" rel="noopener noreferrer">Fale comigo <b>↗</b></a></nav>
  <header className="pricing-hero cosmic-edge"><BackgroundVideo/><div className="projects-cosmic-overlay"/><p>INVESTIMENTO</p><h1>Escolha o site ideal<br/><em>para o momento da sua empresa.</em></h1><span>Três opções de projeto, com escopos claros e a mesma preocupação com qualidade, responsividade e experiência do cliente.</span></header>
  <section className="commercial section pricing-content">
    <div className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<span className="plan-badge">Mais escolhido</span>}<p>{plan.name.toUpperCase()}</p><h3>{plan.price}</h3><div className="plan-rule"/><h4>{plan.headline}</h4><strong>{plan.description}</strong><div className="plan-ideal"><span>IDEAL PARA:</span>{plan.ideal}</div><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul><p className="plan-note">{plan.note}</p><p className="plan-deadline">{plan.deadline}</p><a className={`button ${plan.featured?"solid":"outline"}`} href={whatsapp(plan.message)} target="_blank" rel="noopener noreferrer">{plan.button}</a></article>)}</div>
    <aside className="landing-offer"><div><p>PRECISA VENDER UM SERVIÇO ESPECÍFICO?</p><h3>Uma página focada em uma única ação.</h3><span>Se o objetivo é anunciar ou gerar contatos para um serviço, produto ou campanha específica, uma Landing Page pode ser a melhor escolha.<br/><br/>Criamos páginas focadas em uma única ação, como solicitar orçamento, agendar uma avaliação ou falar com sua empresa.</span></div><a className="button outline" href={whatsapp("Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre uma Landing Page.")} target="_blank" rel="noopener noreferrer">Conversar sobre Landing Page</a></aside>
    <section className="plan-comparison"><header><p>ESCOLHA RÁPIDA</p><h3>Qual é o site ideal para você?</h3></header><div>{comparison.map(option=><article className={option.featured?"featured":""} key={option.name}>{option.featured&&<span className="comparison-badge">Mais escolhido</span>}<p>{option.name}</p><blockquote>“{option.statement}”</blockquote><strong>→ {option.value}</strong></article>)}</div></section>
    <div className="common-rules"><p>REGRAS COMUNS AOS TRÊS PLANOS</p><div>{commonRules.map(rule=><span key={rule}>{rule}</span>)}</div></div>
    <div className="care-section"><header><p>CUIDADO CONTÍNUO</p><h3>Seu site continua cuidado <em>depois da publicação.</em></h3><span>Os dois planos incluem hospedagem, domínio anual, monitoramento e backup. Você escolhe apenas o tempo mensal para correções e o período de atendimento mais adequado para sua empresa.</span></header><div className="care-grid two-plans">{carePlans.map(plan=><article className={plan.featured?"featured":""} key={plan.name}>{plan.featured&&<span className="plan-badge">Mais escolhido</span>}<p>{plan.name}</p><h4>{plan.price}<small>/mês</small></h4><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div><div className="care-included"><strong>Sem cobranças extras dentro do plano</strong><span>Hospedagem, renovação anual do domínio, correções e alterações simples dentro do tempo mensal já estão incluídas.</span></div><small>Alterações não utilizadas não são acumulativas. Novas páginas, seções, identidades visuais, funcionalidades ou integrações fora do escopo são orçadas separadamente.</small></div>
  </section>
  <section className="projects-cta cosmic-edge"><BackgroundVideo flip/><div className="projects-cosmic-overlay"/><p>PRONTO PARA CONVERSAR?</p><h2>Vamos definir o site<br/><em>certo para sua empresa.</em></h2><a href={whatsapp("Olá, Vinicius! Analisei as opções e gostaria de conversar sobre meu projeto.")} target="_blank" rel="noopener noreferrer">CONVERSAR PELO WHATSAPP ↗</a></section>
  <a className="whatsapp-float is-compact" href={whatsapp("Olá, Vinicius! Analisei as opções e gostaria de conversar sobre meu projeto.")} target="_blank" rel="noopener noreferrer" aria-label="Conversar com Vinicius pelo WhatsApp"><span className="whatsapp-copy"><b>Seu próximo site começa aqui</b><small>Conte sua ideia pelo WhatsApp</small></span><i className="whatsapp-icon"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.5 12.5 0 0 0-10.7 19L3.6 28.4l6.5-1.7A12.5 12.5 0 1 0 16 3Zm0 22.7c-2 0-3.8-.5-5.4-1.5l-.4-.2-3.8 1 1-3.7-.2-.4A10.2 10.2 0 1 1 16 25.7Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1a8.4 8.4 0 0 1-4.1-3.6c-.3-.5.3-.5.9-1.6.1-.2.1-.4 0-.6l-.9-2.2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.3 3.4 1.5 3.6c.2.2 2.5 3.8 6 5.3.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.7.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg></i></a>
</main>}
