"use client";
const whatsapp="https://wa.me/5511918554289?text=Olá%20Vinicius%2C%20vi%20seu%20portfólio%20e%20quero%20conversar%20sobre%20um%20site.";
const projects=[
 {id:"wi-fiber",title:"WI FIBER",category:"Telecom",image:"/projects/wi-fiber.png",favicon:"/projects/favicons/wi-fiber.png",live:"https://wi-fiber.vercel.app/",kind:"Redesign de site existente",objective:"Modernizar a presença digital e tornar planos, cobertura e canais de atendimento mais fáceis de encontrar.",experience:"Uma interface atual, com hierarquia clara, chamadas para ação bem distribuídas e uma jornada comercial direta.",tags:["Redesign","UX","Responsivo"]},
 {id:"meu-mundo-colorido",title:"Meu Mundo Colorido",category:"Educação infantil",image:"/projects/meu-mundo-colorido.png",favicon:"/projects/favicons/meu-mundo-colorido.svg",live:"https://meumundocolorido.vercel.app/",kind:"Projeto criado do zero",objective:"Apresentar o espaço infantil de forma acolhedora e transmitir segurança para as famílias desde o primeiro contato.",experience:"Cores, formas e conteúdo trabalham juntos para criar uma experiência alegre, afetiva e simples de navegar.",tags:["Estratégia","Identidade","Responsivo"]},
 {id:"clínica-zauli",title:"Clínica Zauli",category:"Odontologia",image:"/projects/clinica-zauli.png",favicon:undefined,live:"https://clinicazauli-el3c.vercel.app/",kind:"Projeto criado do zero",objective:"Fortalecer o posicionamento profissional da clínica e transformar credibilidade em intenção de agendamento.",experience:"Uma experiência sofisticada e humana, com leitura confortável, identidade consistente e foco nos tratamentos.",tags:["UX","Autoridade","Conversão"]},
 {id:"atsoc",title:"ATSOC",category:"Serviços para provedores",image:"/projects/atsoc.png",favicon:undefined,live:"https://www.atsoc.com.br/",kind:"Projeto criado do zero",objective:"Explicar uma solução especializada de suporte de forma clara para gestores de provedores de internet.",experience:"Conteúdo comercial estruturado para reduzir dúvidas, demonstrar valor e conduzir o visitante ao diagnóstico.",tags:["Copy","Estratégia","Conversão"]}
];
function Preview({title,live,favicon}:{title:string;live:string;favicon?:string}){return <div className="site-preview"><div className="preview-head"><div><span className="preview-icon"><b>VS</b>{favicon&&<img src={favicon} alt={`Favicon do projeto ${title}`}/>}</span><p><b>{title}</b><small>Site real e navegável</small></p></div><div className="preview-actions"><span>ROLE PARA EXPLORAR ↓</span><a href={live} target="_blank" rel="noreferrer">ABRIR SITE ↗</a></div></div><div className="detail-browser"><div className="browser-bar"><div><i/><i/><i/></div><span>{live.replace("https://","")}</span><b>↗</b></div><iframe className="live-frame" src={live} title={`Visualização do site ${title}`} loading="lazy"/></div></div>}
export default function Projetos(){return <main className="projects-page">
  <nav className="projects-nav"><a className="logo" href="/"><span>VS</span></a><a href="/">VOLTAR PARA O PORTFÓLIO</a><a href={whatsapp} target="_blank" rel="noreferrer">FALAR COMIGO ↗</a></nav>
  <header className="projects-hero"><p>PROJETOS SELECIONADOS</p><h1>Do desafio à<br/><em>experiência digital.</em></h1><span>Conheça o contexto, as decisões e o resultado de cada projeto.</span></header>
  <section className="projects-detail">{projects.map((project,index)=><article id={project.id} key={project.id} className="detail-case">
    <div className="detail-head"><span>0{index+1} DE 0{projects.length}</span><span>{project.kind}</span></div>
    <div className="detail-title"><div><p>{project.category}</p><h2>{project.title}</h2></div><div className="detail-summary"><span>OBJETIVO</span><p>{project.objective}</p><span>EXPERIÊNCIA CRIADA</span><p>{project.experience}</p><div>{project.tags.map(tag=><b key={tag}>{tag}</b>)}</div></div></div>
    {index===0&&<div className="comparison"><div><span>ANTES</span><div className="comparison-image"><img src="/projects/wi-fiber-before.png" alt="Site antigo da WI FIBER"/></div><p>Visual desatualizado, excesso de elementos concorrendo pela atenção e pouca clareza na jornada comercial.</p></div><i>→</i><div><span>DEPOIS</span><div className="comparison-image"><img src={project.image} alt="Redesign do site WI FIBER"/></div><p>Mensagem forte, organização visual, acesso rápido aos serviços e chamadas para ação mais evidentes.</p></div></div>}
    <Preview title={project.title} live={project.live} favicon={project.favicon}/>
  </article>)}</section>
  <footer className="projects-cta"><p>SEU NEGÓCIO PODE SER O PRÓXIMO</p><h2>Vamos criar uma presença<br/><em>que gere confiança.</em></h2><a href={whatsapp} target="_blank" rel="noreferrer">CONVERSAR PELO WHATSAPP ↗</a></footer><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Conversar com Vinicius pelo WhatsApp"><span className="whatsapp-copy"><b>Seu próximo site começa aqui</b><small>Conte sua ideia pelo WhatsApp</small></span><i className="whatsapp-icon"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.5 12.5 0 0 0-10.7 19L3.6 28.4l6.5-1.7A12.5 12.5 0 1 0 16 3Zm0 22.7c-2 0-3.8-.5-5.4-1.5l-.4-.2-3.8 1 1-3.7-.2-.4A10.2 10.2 0 1 1 16 25.7Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1a8.4 8.4 0 0 1-4.1-3.6c-.3-.5.3-.5.9-1.6.1-.2.1-.4 0-.6l-.9-2.2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.3 3.4 1.5 3.6c.2.2 2.5 3.8 6 5.3.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.7.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg></i></a>
</main>}
